import corePlugins from './utilities-a-la-carte/plugins.js';

/** @type {import('tailwindcss').Config} */
export default {
  corePlugins: Object.assign(corePlugins, {
    display: true,
    visibility: true,
    flexBasis: true,
    flexDirection: true,
    flexWrap: true,
    flex: true,
    flexGrow: true,
    flexShrink: true,
    order: true,
    gridTemplateColumns: true,
    gridColumn: true,
    gridColumnStart: true,
    gridColumnEnd: true,
    gridTemplateRows: true,
    gridRow: true,
    gridRowStart: true,
    gridRowEnd: true,
    gridAutoFlow: true,
    gridAutoColumns: true,
    gridAutoRows: true,
    gap: true,
    justifyContent: true,
    justifyItems: true,
    justifySelf: true,
    alignContent: true,
    alignItems: true,
    alignSelf: true,
    placeContent: true,
    placeItems: true,
    placeSelf: true,
    padding: true,
    margin: true,
    space: true,
    width: true,
    minWidth: true,
    maxWidth: true,
    height: true,
    maxHeight: true,
    minHeight: true,
    size: true,
    position: true,
    inset: true,
    textAlign: true,
    fontSize: true,
    fontWeight: true,
    fontStyle: true,
    textTransform: true,
    lineHeight: true,
    letterSpacing: true,
    borderWidth: true,
    borderStyle: true,
  }),
  content: [],
  safelist: [{ pattern: /./, variants: ['sm', 'md', 'lg', 'xl'] }],
  theme: {
    extend: {},
  },
  plugins: [],
};
